version: 2

config: &config
  working_directory: ~/danger
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 1
  environment:
    TERM: dumb

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

jobs:
  check:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: build/reports/test-results
      - store_artifacts:
          path: build/reports/
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - run:
          name: Danger
          command: bundle exec danger

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  assemble:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assemble

workflows:
  version: 2
  danger_check_assemble:
    jobs:
      - check
      - assemble:
          requires:
            - check