version: 2

config: &config
  working_directory: ~/danger
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 1
  environment:
    TERM: dumb

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

jobs:
  check:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check detekt test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: build/reports/test-results
      - store_artifacts:
          path: build/reports/
      - run: &bundle_install_for_danger
          name: Bundle install
          command: |
            cd script/danger
            bundle check || bundle install
      - run:
          name: Danger assertions
          command: script/danger_assert

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  assemble:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs
      - run:
          name: Fetch lastet release
          command: script/download_latest_apk latest-release.apk
      - run: *bundle_install_for_danger
      - run:
          name: Danger APK stats
          command: script/danger_compare_apk

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.3
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/app/build/outputs/apk/release/danger-0.3-release-unsigned.apk

workflows:
  version: 2
  danger_check_assemble:
    jobs:
      - check
      - assemble:
          requires:
            - check
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+$/