version: 2

aliases:
  - &restore_gradle_cache
    key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  - &save_gradle_cache
    key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

config: &config
  working_directory: ~/danger
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 1
  environment:
    TERM: dumb

jobs:
  check:
    <<: *config

    steps:
      - checkout
      - restore_cache: *restore_gradle_cache

      - run:
          name: Check
          command: ./gradlew check detekt test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: build/reports/test-results
      - store_artifacts:
          path: build/reports/
      - run: &bundle_install_for_danger
          name: Bundle install
          command: |
            cd script/danger
            bundle check || bundle install
      - run:
          name: Danger assertions
          command: script/danger_assert

      - save_cache: *save_gradle_cache

  assemble:
    <<: *config

    steps:
      - checkout
      - restore_cache: *restore_gradle_cache

      - run:
          name: Assemble
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs
      - persist_to_workspace:
          root: app
          paths:
            - build/outputs
      - run:
          name: Fetch lastet release
          command: script/download_latest_apk latest-release.apk
      - run: *bundle_install_for_danger
      - run:
          name: Danger APK stats
          command: script/danger_compare_apk

      - save_cache: *save_gradle_cache

  publish-github-release:
    working_directory: ~/danger
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: app
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${DANGER_GITHUB_API_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} app/build/outputs/apk/release/danger-0.3-release-unsigned.apk

workflows:
  version: 2
  danger_check_assemble:
    jobs:
      - check:
          filters:
            tags:
              only: /^\d+\.\d+$/
      - assemble:
          requires:
            - check
          filters:
            tags:
              only: /^\d+\.\d+$/
      - publish-github-release:
          requires:
            - assemble
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+$/