version: 2

config: &config
  working_directory: ~/danger
  docker:
    - image: circleci/android:api-28-alpha
  parallelism: 4
  environment:
    TERM: dumb

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}

jobs:
  check:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Check
          command: ./gradlew check test
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: build/reports/test-results
      - store_artifacts:
          path: build/reports/

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  build:
    <<: *config

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Build
          command: ./gradlew build

workflows:
  version: 2
  check_build:
    jobs:
      - check
      - build:
          requires:
            - check